/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';

/**
 * 
 * @export
 * @interface ActivateSessionResponse
 */
export interface ActivateSessionResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof ActivateSessionResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {string}
     * @memberof ActivateSessionResponse
     */
    ServerNonce?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivateSessionResponse
     */
    Results?: Array<number>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof ActivateSessionResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the ActivateSessionResponse interface.
 */
export function instanceOfActivateSessionResponse(value: object): value is ActivateSessionResponse {
    return true;
}

export function ActivateSessionResponseFromJSON(json: any): ActivateSessionResponse {
    return ActivateSessionResponseFromJSONTyped(json, false);
}

export function ActivateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'ServerNonce': json['ServerNonce'] == null ? undefined : json['ServerNonce'],
        'Results': json['Results'] == null ? undefined : json['Results'],
        'DiagnosticInfos': json['DiagnosticInfos'] == null ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

  export function ActivateSessionResponseToJSON(json: any): ActivateSessionResponse {
      return ActivateSessionResponseToJSONTyped(json, false);
  }

  export function ActivateSessionResponseToJSONTyped(value?: ActivateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'ServerNonce': value['ServerNonce'],
        'Results': value['Results'],
        'DiagnosticInfos': value['DiagnosticInfos'] == null ? undefined : ((value['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

