/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnonymousIdentityToken
 */
export interface AnonymousIdentityToken {
    /**
     * 
     * @type {string}
     * @memberof AnonymousIdentityToken
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the AnonymousIdentityToken interface.
 */
export function instanceOfAnonymousIdentityToken(value: object): value is AnonymousIdentityToken {
    return true;
}

export function AnonymousIdentityTokenFromJSON(json: any): AnonymousIdentityToken {
    return AnonymousIdentityTokenFromJSONTyped(json, false);
}

export function AnonymousIdentityTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonymousIdentityToken {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function AnonymousIdentityTokenToJSON(json: any): AnonymousIdentityToken {
      return AnonymousIdentityTokenToJSONTyped(json, false);
  }

  export function AnonymousIdentityTokenToJSONTyped(value?: AnonymousIdentityToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

