/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrowseDescription
 */
export interface BrowseDescription {
    /**
     * 
     * @type {string}
     * @memberof BrowseDescription
     */
    NodeId?: string;
    /**
     * 
     * @type {number}
     * @memberof BrowseDescription
     */
    BrowseDirection?: number;
    /**
     * 
     * @type {string}
     * @memberof BrowseDescription
     */
    ReferenceTypeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BrowseDescription
     */
    IncludeSubtypes?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BrowseDescription
     */
    NodeClassMask?: number;
    /**
     * 
     * @type {number}
     * @memberof BrowseDescription
     */
    ResultMask?: number;
}

/**
 * Check if a given object implements the BrowseDescription interface.
 */
export function instanceOfBrowseDescription(value: object): value is BrowseDescription {
    return true;
}

export function BrowseDescriptionFromJSON(json: any): BrowseDescription {
    return BrowseDescriptionFromJSONTyped(json, false);
}

export function BrowseDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'NodeId': json['NodeId'] == null ? undefined : json['NodeId'],
        'BrowseDirection': json['BrowseDirection'] == null ? undefined : json['BrowseDirection'],
        'ReferenceTypeId': json['ReferenceTypeId'] == null ? undefined : json['ReferenceTypeId'],
        'IncludeSubtypes': json['IncludeSubtypes'] == null ? undefined : json['IncludeSubtypes'],
        'NodeClassMask': json['NodeClassMask'] == null ? undefined : json['NodeClassMask'],
        'ResultMask': json['ResultMask'] == null ? undefined : json['ResultMask'],
    };
}

  export function BrowseDescriptionToJSON(json: any): BrowseDescription {
      return BrowseDescriptionToJSONTyped(json, false);
  }

  export function BrowseDescriptionToJSONTyped(value?: BrowseDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NodeId': value['NodeId'],
        'BrowseDirection': value['BrowseDirection'],
        'ReferenceTypeId': value['ReferenceTypeId'],
        'IncludeSubtypes': value['IncludeSubtypes'],
        'NodeClassMask': value['NodeClassMask'],
        'ResultMask': value['ResultMask'],
    };
}

