/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceDescription } from './ReferenceDescription';
import {
    ReferenceDescriptionFromJSON,
    ReferenceDescriptionFromJSONTyped,
    ReferenceDescriptionToJSON,
    ReferenceDescriptionToJSONTyped,
} from './ReferenceDescription';

/**
 * 
 * @export
 * @interface BrowseResult
 */
export interface BrowseResult {
    /**
     * 
     * @type {number}
     * @memberof BrowseResult
     */
    StatusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof BrowseResult
     */
    ContinuationPoint?: string;
    /**
     * 
     * @type {Array<ReferenceDescription>}
     * @memberof BrowseResult
     */
    References?: Array<ReferenceDescription>;
}

/**
 * Check if a given object implements the BrowseResult interface.
 */
export function instanceOfBrowseResult(value: object): value is BrowseResult {
    return true;
}

export function BrowseResultFromJSON(json: any): BrowseResult {
    return BrowseResultFromJSONTyped(json, false);
}

export function BrowseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'StatusCode': json['StatusCode'] == null ? undefined : json['StatusCode'],
        'ContinuationPoint': json['ContinuationPoint'] == null ? undefined : json['ContinuationPoint'],
        'References': json['References'] == null ? undefined : ((json['References'] as Array<any>).map(ReferenceDescriptionFromJSON)),
    };
}

  export function BrowseResultToJSON(json: any): BrowseResult {
      return BrowseResultToJSONTyped(json, false);
  }

  export function BrowseResultToJSONTyped(value?: BrowseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'StatusCode': value['StatusCode'],
        'ContinuationPoint': value['ContinuationPoint'],
        'References': value['References'] == null ? undefined : ((value['References'] as Array<any>).map(ReferenceDescriptionToJSON)),
    };
}

