/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionTransportDataType
 */
export interface ConnectionTransportDataType {
    /**
     * 
     * @type {string}
     * @memberof ConnectionTransportDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the ConnectionTransportDataType interface.
 */
export function instanceOfConnectionTransportDataType(value: object): value is ConnectionTransportDataType {
    return true;
}

export function ConnectionTransportDataTypeFromJSON(json: any): ConnectionTransportDataType {
    return ConnectionTransportDataTypeFromJSONTyped(json, false);
}

export function ConnectionTransportDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionTransportDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function ConnectionTransportDataTypeToJSON(json: any): ConnectionTransportDataType {
      return ConnectionTransportDataTypeToJSONTyped(json, false);
  }

  export function ConnectionTransportDataTypeToJSONTyped(value?: ConnectionTransportDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

