/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonitoredItemCreateRequest } from './MonitoredItemCreateRequest';
import {
    MonitoredItemCreateRequestFromJSON,
    MonitoredItemCreateRequestFromJSONTyped,
    MonitoredItemCreateRequestToJSON,
    MonitoredItemCreateRequestToJSONTyped,
} from './MonitoredItemCreateRequest';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface CreateMonitoredItemsRequest
 */
export interface CreateMonitoredItemsRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof CreateMonitoredItemsRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof CreateMonitoredItemsRequest
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateMonitoredItemsRequest
     */
    TimestampsToReturn?: number;
    /**
     * 
     * @type {Array<MonitoredItemCreateRequest>}
     * @memberof CreateMonitoredItemsRequest
     */
    ItemsToCreate?: Array<MonitoredItemCreateRequest>;
    /**
     * 
     * @type {string}
     * @memberof CreateMonitoredItemsRequest
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the CreateMonitoredItemsRequest interface.
 */
export function instanceOfCreateMonitoredItemsRequest(value: object): value is CreateMonitoredItemsRequest {
    return true;
}

export function CreateMonitoredItemsRequestFromJSON(json: any): CreateMonitoredItemsRequest {
    return CreateMonitoredItemsRequestFromJSONTyped(json, false);
}

export function CreateMonitoredItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonitoredItemsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': json['SubscriptionId'] == null ? undefined : json['SubscriptionId'],
        'TimestampsToReturn': json['TimestampsToReturn'] == null ? undefined : json['TimestampsToReturn'],
        'ItemsToCreate': json['ItemsToCreate'] == null ? undefined : ((json['ItemsToCreate'] as Array<any>).map(MonitoredItemCreateRequestFromJSON)),
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function CreateMonitoredItemsRequestToJSON(json: any): CreateMonitoredItemsRequest {
      return CreateMonitoredItemsRequestToJSONTyped(json, false);
  }

  export function CreateMonitoredItemsRequestToJSONTyped(value?: CreateMonitoredItemsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'SubscriptionId': value['SubscriptionId'],
        'TimestampsToReturn': value['TimestampsToReturn'],
        'ItemsToCreate': value['ItemsToCreate'] == null ? undefined : ((value['ItemsToCreate'] as Array<any>).map(MonitoredItemCreateRequestToJSON)),
        'UaTypeId': value['UaTypeId'],
    };
}

