/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSetReaderMessageDataType
 */
export interface DataSetReaderMessageDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetReaderMessageDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the DataSetReaderMessageDataType interface.
 */
export function instanceOfDataSetReaderMessageDataType(value: object): value is DataSetReaderMessageDataType {
    return true;
}

export function DataSetReaderMessageDataTypeFromJSON(json: any): DataSetReaderMessageDataType {
    return DataSetReaderMessageDataTypeFromJSONTyped(json, false);
}

export function DataSetReaderMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetReaderMessageDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function DataSetReaderMessageDataTypeToJSON(json: any): DataSetReaderMessageDataType {
      return DataSetReaderMessageDataTypeToJSONTyped(json, false);
  }

  export function DataSetReaderMessageDataTypeToJSONTyped(value?: DataSetReaderMessageDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

