/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSetWriterMessageDataType
 */
export interface DataSetWriterMessageDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetWriterMessageDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the DataSetWriterMessageDataType interface.
 */
export function instanceOfDataSetWriterMessageDataType(value: object): value is DataSetWriterMessageDataType {
    return true;
}

export function DataSetWriterMessageDataTypeFromJSON(json: any): DataSetWriterMessageDataType {
    return DataSetWriterMessageDataTypeFromJSONTyped(json, false);
}

export function DataSetWriterMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetWriterMessageDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function DataSetWriterMessageDataTypeToJSON(json: any): DataSetWriterMessageDataType {
      return DataSetWriterMessageDataTypeToJSONTyped(json, false);
  }

  export function DataSetWriterMessageDataTypeToJSONTyped(value?: DataSetWriterMessageDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

