/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataTypeDefinition
 */
export interface DataTypeDefinition {
    /**
     * 
     * @type {string}
     * @memberof DataTypeDefinition
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the DataTypeDefinition interface.
 */
export function instanceOfDataTypeDefinition(value: object): value is DataTypeDefinition {
    return true;
}

export function DataTypeDefinitionFromJSON(json: any): DataTypeDefinition {
    return DataTypeDefinitionFromJSONTyped(json, false);
}

export function DataTypeDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataTypeDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function DataTypeDefinitionToJSON(json: any): DataTypeDefinition {
      return DataTypeDefinitionToJSONTyped(json, false);
  }

  export function DataTypeDefinitionToJSONTyped(value?: DataTypeDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

