/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSetWriterTransportDataType
 */
export interface DataSetWriterTransportDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetWriterTransportDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the DataSetWriterTransportDataType interface.
 */
export function instanceOfDataSetWriterTransportDataType(value: object): value is DataSetWriterTransportDataType {
    return true;
}

export function DataSetWriterTransportDataTypeFromJSON(json: any): DataSetWriterTransportDataType {
    return DataSetWriterTransportDataTypeFromJSONTyped(json, false);
}

export function DataSetWriterTransportDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetWriterTransportDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function DataSetWriterTransportDataTypeToJSON(json: any): DataSetWriterTransportDataType {
      return DataSetWriterTransportDataTypeToJSONTyped(json, false);
  }

  export function DataSetWriterTransportDataTypeToJSONTyped(value?: DataSetWriterTransportDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

