/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSetReaderTransportDataType
 */
export interface DataSetReaderTransportDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetReaderTransportDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the DataSetReaderTransportDataType interface.
 */
export function instanceOfDataSetReaderTransportDataType(value: object): value is DataSetReaderTransportDataType {
    return true;
}

export function DataSetReaderTransportDataTypeFromJSON(json: any): DataSetReaderTransportDataType {
    return DataSetReaderTransportDataTypeFromJSONTyped(json, false);
}

export function DataSetReaderTransportDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetReaderTransportDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function DataSetReaderTransportDataTypeToJSON(json: any): DataSetReaderTransportDataType {
      return DataSetReaderTransportDataTypeToJSONTyped(json, false);
  }

  export function DataSetReaderTransportDataTypeToJSONTyped(value?: DataSetReaderTransportDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

