/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * This API provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
} from './LocalizedText';

/**
 * 
 * @export
 * @interface EUInformation
 */
export interface EUInformation {
    /**
     * 
     * @type {string}
     * @memberof EUInformation
     */
    NamespaceUri?: string;
    /**
     * 
     * @type {number}
     * @memberof EUInformation
     */
    UnitId?: number;
    /**
     * 
     * @type {LocalizedText}
     * @memberof EUInformation
     */
    DisplayName?: LocalizedText;
    /**
     * 
     * @type {LocalizedText}
     * @memberof EUInformation
     */
    Description?: LocalizedText;
}

/**
 * Check if a given object implements the EUInformation interface.
 */
export function instanceOfEUInformation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EUInformationFromJSON(json: any): EUInformation {
    return EUInformationFromJSONTyped(json, false);
}

export function EUInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EUInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUri': !exists(json, 'NamespaceUri') ? undefined : json['NamespaceUri'],
        'UnitId': !exists(json, 'UnitId') ? undefined : json['UnitId'],
        'DisplayName': !exists(json, 'DisplayName') ? undefined : LocalizedTextFromJSON(json['DisplayName']),
        'Description': !exists(json, 'Description') ? undefined : LocalizedTextFromJSON(json['Description']),
    };
}

export function EUInformationToJSON(value?: EUInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUri': value.NamespaceUri,
        'UnitId': value.UnitId,
        'DisplayName': LocalizedTextToJSON(value.DisplayName),
        'Description': LocalizedTextToJSON(value.Description),
    };
}

