/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterOperand
 */
export interface FilterOperand {
    /**
     * 
     * @type {string}
     * @memberof FilterOperand
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the FilterOperand interface.
 */
export function instanceOfFilterOperand(value: object): value is FilterOperand {
    return true;
}

export function FilterOperandFromJSON(json: any): FilterOperand {
    return FilterOperandFromJSONTyped(json, false);
}

export function FilterOperandFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterOperand {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function FilterOperandToJSON(json: any): FilterOperand {
      return FilterOperandToJSONTyped(json, false);
  }

  export function FilterOperandToJSONTyped(value?: FilterOperand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

