/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryReadDetails
 */
export interface HistoryReadDetails {
    /**
     * 
     * @type {string}
     * @memberof HistoryReadDetails
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the HistoryReadDetails interface.
 */
export function instanceOfHistoryReadDetails(value: object): value is HistoryReadDetails {
    return true;
}

export function HistoryReadDetailsFromJSON(json: any): HistoryReadDetails {
    return HistoryReadDetailsFromJSONTyped(json, false);
}

export function HistoryReadDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function HistoryReadDetailsToJSON(json: any): HistoryReadDetails {
      return HistoryReadDetailsToJSONTyped(json, false);
  }

  export function HistoryReadDetailsToJSONTyped(value?: HistoryReadDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

