/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryReadValueId
 */
export interface HistoryReadValueId {
    /**
     * 
     * @type {string}
     * @memberof HistoryReadValueId
     */
    NodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryReadValueId
     */
    IndexRange?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryReadValueId
     */
    DataEncoding?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryReadValueId
     */
    ContinuationPoint?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryReadValueId
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the HistoryReadValueId interface.
 */
export function instanceOfHistoryReadValueId(value: object): value is HistoryReadValueId {
    return true;
}

export function HistoryReadValueIdFromJSON(json: any): HistoryReadValueId {
    return HistoryReadValueIdFromJSONTyped(json, false);
}

export function HistoryReadValueIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadValueId {
    if (json == null) {
        return json;
    }
    return {
        
        'NodeId': json['NodeId'] == null ? undefined : json['NodeId'],
        'IndexRange': json['IndexRange'] == null ? undefined : json['IndexRange'],
        'DataEncoding': json['DataEncoding'] == null ? undefined : json['DataEncoding'],
        'ContinuationPoint': json['ContinuationPoint'] == null ? undefined : json['ContinuationPoint'],
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function HistoryReadValueIdToJSON(json: any): HistoryReadValueId {
      return HistoryReadValueIdToJSONTyped(json, false);
  }

  export function HistoryReadValueIdToJSONTyped(value?: HistoryReadValueId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NodeId': value['NodeId'],
        'IndexRange': value['IndexRange'],
        'DataEncoding': value['DataEncoding'],
        'ContinuationPoint': value['ContinuationPoint'],
        'UaTypeId': value['UaTypeId'],
    };
}

