/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonDataSetWriterMessageDataType
 */
export interface JsonDataSetWriterMessageDataType {
    /**
     * 
     * @type {number}
     * @memberof JsonDataSetWriterMessageDataType
     */
    DataSetMessageContentMask?: number;
    /**
     * 
     * @type {string}
     * @memberof JsonDataSetWriterMessageDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the JsonDataSetWriterMessageDataType interface.
 */
export function instanceOfJsonDataSetWriterMessageDataType(value: object): value is JsonDataSetWriterMessageDataType {
    return true;
}

export function JsonDataSetWriterMessageDataTypeFromJSON(json: any): JsonDataSetWriterMessageDataType {
    return JsonDataSetWriterMessageDataTypeFromJSONTyped(json, false);
}

export function JsonDataSetWriterMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonDataSetWriterMessageDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'DataSetMessageContentMask': json['DataSetMessageContentMask'] == null ? undefined : json['DataSetMessageContentMask'],
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function JsonDataSetWriterMessageDataTypeToJSON(json: any): JsonDataSetWriterMessageDataType {
      return JsonDataSetWriterMessageDataTypeToJSONTyped(json, false);
  }

  export function JsonDataSetWriterMessageDataTypeToJSONTyped(value?: JsonDataSetWriterMessageDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'DataSetMessageContentMask': value['DataSetMessageContentMask'],
        'UaTypeId': value['UaTypeId'],
    };
}

