/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonitoringFilterResult
 */
export interface MonitoringFilterResult {
    /**
     * 
     * @type {string}
     * @memberof MonitoringFilterResult
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the MonitoringFilterResult interface.
 */
export function instanceOfMonitoringFilterResult(value: object): value is MonitoringFilterResult {
    return true;
}

export function MonitoringFilterResultFromJSON(json: any): MonitoringFilterResult {
    return MonitoringFilterResultFromJSONTyped(json, false);
}

export function MonitoringFilterResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoringFilterResult {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function MonitoringFilterResultToJSON(json: any): MonitoringFilterResult {
      return MonitoringFilterResultToJSONTyped(json, false);
  }

  export function MonitoringFilterResultToJSONTyped(value?: MonitoringFilterResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

