/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonitoringFilter
 */
export interface MonitoringFilter {
    /**
     * 
     * @type {string}
     * @memberof MonitoringFilter
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the MonitoringFilter interface.
 */
export function instanceOfMonitoringFilter(value: object): value is MonitoringFilter {
    return true;
}

export function MonitoringFilterFromJSON(json: any): MonitoringFilter {
    return MonitoringFilterFromJSONTyped(json, false);
}

export function MonitoringFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoringFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function MonitoringFilterToJSON(json: any): MonitoringFilter {
      return MonitoringFilterToJSONTyped(json, false);
  }

  export function MonitoringFilterToJSONTyped(value?: MonitoringFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

