/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonitoringParameters } from './MonitoringParameters';
import {
    MonitoringParametersFromJSON,
    MonitoringParametersFromJSONTyped,
    MonitoringParametersToJSON,
    MonitoringParametersToJSONTyped,
} from './MonitoringParameters';

/**
 * 
 * @export
 * @interface MonitoredItemModifyRequest
 */
export interface MonitoredItemModifyRequest {
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemModifyRequest
     */
    MonitoredItemId?: number;
    /**
     * 
     * @type {MonitoringParameters}
     * @memberof MonitoredItemModifyRequest
     */
    RequestedParameters?: MonitoringParameters;
    /**
     * 
     * @type {string}
     * @memberof MonitoredItemModifyRequest
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the MonitoredItemModifyRequest interface.
 */
export function instanceOfMonitoredItemModifyRequest(value: object): value is MonitoredItemModifyRequest {
    return true;
}

export function MonitoredItemModifyRequestFromJSON(json: any): MonitoredItemModifyRequest {
    return MonitoredItemModifyRequestFromJSONTyped(json, false);
}

export function MonitoredItemModifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemModifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'MonitoredItemId': json['MonitoredItemId'] == null ? undefined : json['MonitoredItemId'],
        'RequestedParameters': json['RequestedParameters'] == null ? undefined : MonitoringParametersFromJSON(json['RequestedParameters']),
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function MonitoredItemModifyRequestToJSON(json: any): MonitoredItemModifyRequest {
      return MonitoredItemModifyRequestToJSONTyped(json, false);
  }

  export function MonitoredItemModifyRequestToJSONTyped(value?: MonitoredItemModifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MonitoredItemId': value['MonitoredItemId'],
        'RequestedParameters': MonitoringParametersToJSON(value['RequestedParameters']),
        'UaTypeId': value['UaTypeId'],
    };
}

