/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationData
 */
export interface NotificationData {
    /**
     * 
     * @type {string}
     * @memberof NotificationData
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the NotificationData interface.
 */
export function instanceOfNotificationData(value: object): value is NotificationData {
    return true;
}

export function NotificationDataFromJSON(json: any): NotificationData {
    return NotificationDataFromJSONTyped(json, false);
}

export function NotificationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationData {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function NotificationDataToJSON(json: any): NotificationData {
      return NotificationDataToJSONTyped(json, false);
  }

  export function NotificationDataToJSONTyped(value?: NotificationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

