/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * This API provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Range
 */
export interface Range {
    /**
     * 
     * @type {number}
     * @memberof Range
     */
    Low?: number;
    /**
     * 
     * @type {number}
     * @memberof Range
     */
    High?: number;
}

/**
 * Check if a given object implements the Range interface.
 */
export function instanceOfRange(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RangeFromJSON(json: any): Range {
    return RangeFromJSONTyped(json, false);
}

export function RangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Range {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Low': !exists(json, 'Low') ? undefined : json['Low'],
        'High': !exists(json, 'High') ? undefined : json['High'],
    };
}

export function RangeToJSON(value?: Range | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Low': value.Low,
        'High': value.High,
    };
}

