/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReaderGroupMessageDataType
 */
export interface ReaderGroupMessageDataType {
    /**
     * 
     * @type {string}
     * @memberof ReaderGroupMessageDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the ReaderGroupMessageDataType interface.
 */
export function instanceOfReaderGroupMessageDataType(value: object): value is ReaderGroupMessageDataType {
    return true;
}

export function ReaderGroupMessageDataTypeFromJSON(json: any): ReaderGroupMessageDataType {
    return ReaderGroupMessageDataTypeFromJSONTyped(json, false);
}

export function ReaderGroupMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReaderGroupMessageDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function ReaderGroupMessageDataTypeToJSON(json: any): ReaderGroupMessageDataType {
      return ReaderGroupMessageDataTypeToJSONTyped(json, false);
  }

  export function ReaderGroupMessageDataTypeToJSONTyped(value?: ReaderGroupMessageDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

