/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface RegisterNodesRequest
 */
export interface RegisterNodesRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof RegisterNodesRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesRequest
     */
    NodesToRegister?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RegisterNodesRequest
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the RegisterNodesRequest interface.
 */
export function instanceOfRegisterNodesRequest(value: object): value is RegisterNodesRequest {
    return true;
}

export function RegisterNodesRequestFromJSON(json: any): RegisterNodesRequest {
    return RegisterNodesRequestFromJSONTyped(json, false);
}

export function RegisterNodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNodesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'NodesToRegister': json['NodesToRegister'] == null ? undefined : json['NodesToRegister'],
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function RegisterNodesRequestToJSON(json: any): RegisterNodesRequest {
      return RegisterNodesRequestToJSONTyped(json, false);
  }

  export function RegisterNodesRequestToJSONTyped(value?: RegisterNodesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'NodesToRegister': value['NodesToRegister'],
        'UaTypeId': value['UaTypeId'],
    };
}

