/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelativePathElement } from './RelativePathElement';
import {
    RelativePathElementFromJSON,
    RelativePathElementFromJSONTyped,
    RelativePathElementToJSON,
    RelativePathElementToJSONTyped,
} from './RelativePathElement';

/**
 * 
 * @export
 * @interface RelativePath
 */
export interface RelativePath {
    /**
     * 
     * @type {Array<RelativePathElement>}
     * @memberof RelativePath
     */
    Elements?: Array<RelativePathElement>;
    /**
     * 
     * @type {string}
     * @memberof RelativePath
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the RelativePath interface.
 */
export function instanceOfRelativePath(value: object): value is RelativePath {
    return true;
}

export function RelativePathFromJSON(json: any): RelativePath {
    return RelativePathFromJSONTyped(json, false);
}

export function RelativePathFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelativePath {
    if (json == null) {
        return json;
    }
    return {
        
        'Elements': json['Elements'] == null ? undefined : ((json['Elements'] as Array<any>).map(RelativePathElementFromJSON)),
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function RelativePathToJSON(json: any): RelativePath {
      return RelativePathToJSONTyped(json, false);
  }

  export function RelativePathToJSONTyped(value?: RelativePath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Elements': value['Elements'] == null ? undefined : ((value['Elements'] as Array<any>).map(RelativePathElementToJSON)),
        'UaTypeId': value['UaTypeId'],
    };
}

