/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';

/**
 * 
 * @export
 * @interface SetTriggeringResponse
 */
export interface SetTriggeringResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof SetTriggeringResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetTriggeringResponse
     */
    AddResults?: Array<number>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof SetTriggeringResponse
     */
    AddDiagnosticInfos?: Array<DiagnosticInfo>;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetTriggeringResponse
     */
    RemoveResults?: Array<number>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof SetTriggeringResponse
     */
    RemoveDiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the SetTriggeringResponse interface.
 */
export function instanceOfSetTriggeringResponse(value: object): value is SetTriggeringResponse {
    return true;
}

export function SetTriggeringResponseFromJSON(json: any): SetTriggeringResponse {
    return SetTriggeringResponseFromJSONTyped(json, false);
}

export function SetTriggeringResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetTriggeringResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'AddResults': json['AddResults'] == null ? undefined : json['AddResults'],
        'AddDiagnosticInfos': json['AddDiagnosticInfos'] == null ? undefined : ((json['AddDiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
        'RemoveResults': json['RemoveResults'] == null ? undefined : json['RemoveResults'],
        'RemoveDiagnosticInfos': json['RemoveDiagnosticInfos'] == null ? undefined : ((json['RemoveDiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

  export function SetTriggeringResponseToJSON(json: any): SetTriggeringResponse {
      return SetTriggeringResponseToJSONTyped(json, false);
  }

  export function SetTriggeringResponseToJSONTyped(value?: SetTriggeringResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'AddResults': value['AddResults'],
        'AddDiagnosticInfos': value['AddDiagnosticInfos'] == null ? undefined : ((value['AddDiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
        'RemoveResults': value['RemoveResults'],
        'RemoveDiagnosticInfos': value['RemoveDiagnosticInfos'] == null ? undefined : ((value['RemoveDiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

