/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusCodeType
 */
export interface StatusCodeType {
    /**
     * 
     * @type {number}
     * @memberof StatusCodeType
     */
    Code?: number;
    /**
     * 
     * @type {string}
     * @memberof StatusCodeType
     */
    Symbol?: string;
}

/**
 * Check if a given object implements the StatusCodeType interface.
 */
export function instanceOfStatusCodeType(value: object): value is StatusCodeType {
    return true;
}

export function StatusCodeTypeFromJSON(json: any): StatusCodeType {
    return StatusCodeTypeFromJSONTyped(json, false);
}

export function StatusCodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusCodeType {
    if (json == null) {
        return json;
    }
    return {
        
        'Code': json['Code'] == null ? undefined : json['Code'],
        'Symbol': json['Symbol'] == null ? undefined : json['Symbol'],
    };
}

  export function StatusCodeTypeToJSON(json: any): StatusCodeType {
      return StatusCodeTypeToJSONTyped(json, false);
  }

  export function StatusCodeTypeToJSONTyped(value?: StatusCodeType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Code': value['Code'],
        'Symbol': value['Symbol'],
    };
}

