/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Structure
 */
export interface Structure {
    /**
     * 
     * @type {string}
     * @memberof Structure
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the Structure interface.
 */
export function instanceOfStructure(value: object): value is Structure {
    return true;
}

export function StructureFromJSON(json: any): Structure {
    return StructureFromJSONTyped(json, false);
}

export function StructureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Structure {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function StructureToJSON(json: any): Structure {
      return StructureToJSONTyped(json, false);
  }

  export function StructureToJSONTyped(value?: Structure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

