/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribedDataSetDataType
 */
export interface SubscribedDataSetDataType {
    /**
     * 
     * @type {string}
     * @memberof SubscribedDataSetDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the SubscribedDataSetDataType interface.
 */
export function instanceOfSubscribedDataSetDataType(value: object): value is SubscribedDataSetDataType {
    return true;
}

export function SubscribedDataSetDataTypeFromJSON(json: any): SubscribedDataSetDataType {
    return SubscribedDataSetDataTypeFromJSONTyped(json, false);
}

export function SubscribedDataSetDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribedDataSetDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function SubscribedDataSetDataTypeToJSON(json: any): SubscribedDataSetDataType {
      return SubscribedDataSetDataTypeToJSONTyped(json, false);
  }

  export function SubscribedDataSetDataTypeToJSONTyped(value?: SubscribedDataSetDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

