/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionAcknowledgement
 */
export interface SubscriptionAcknowledgement {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionAcknowledgement
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionAcknowledgement
     */
    SequenceNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAcknowledgement
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the SubscriptionAcknowledgement interface.
 */
export function instanceOfSubscriptionAcknowledgement(value: object): value is SubscriptionAcknowledgement {
    return true;
}

export function SubscriptionAcknowledgementFromJSON(json: any): SubscriptionAcknowledgement {
    return SubscriptionAcknowledgementFromJSONTyped(json, false);
}

export function SubscriptionAcknowledgementFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionAcknowledgement {
    if (json == null) {
        return json;
    }
    return {
        
        'SubscriptionId': json['SubscriptionId'] == null ? undefined : json['SubscriptionId'],
        'SequenceNumber': json['SequenceNumber'] == null ? undefined : json['SequenceNumber'],
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function SubscriptionAcknowledgementToJSON(json: any): SubscriptionAcknowledgement {
      return SubscriptionAcknowledgementToJSONTyped(json, false);
  }

  export function SubscriptionAcknowledgementToJSONTyped(value?: SubscriptionAcknowledgement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'SubscriptionId': value['SubscriptionId'],
        'SequenceNumber': value['SequenceNumber'],
        'UaTypeId': value['UaTypeId'],
    };
}

