/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Union
 */
export interface Union {
    /**
     * 
     * @type {number}
     * @memberof Union
     */
    SwitchField?: number;
}

/**
 * Check if a given object implements the Union interface.
 */
export function instanceOfUnion(value: object): value is Union {
    return true;
}

export function UnionFromJSON(json: any): Union {
    return UnionFromJSONTyped(json, false);
}

export function UnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Union {
    if (json == null) {
        return json;
    }
    return {
        
        'SwitchField': json['SwitchField'] == null ? undefined : json['SwitchField'],
    };
}

  export function UnionToJSON(json: any): Union {
      return UnionToJSONTyped(json, false);
  }

  export function UnionToJSONTyped(value?: Union | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'SwitchField': value['SwitchField'],
    };
}

