/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserIdentityToken
 */
export interface UserIdentityToken {
    /**
     * 
     * @type {string}
     * @memberof UserIdentityToken
     */
    PolicyId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserIdentityToken
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the UserIdentityToken interface.
 */
export function instanceOfUserIdentityToken(value: object): value is UserIdentityToken {
    return true;
}

export function UserIdentityTokenFromJSON(json: any): UserIdentityToken {
    return UserIdentityTokenFromJSONTyped(json, false);
}

export function UserIdentityTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentityToken {
    if (json == null) {
        return json;
    }
    return {
        
        'PolicyId': json['PolicyId'] == null ? undefined : json['PolicyId'],
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function UserIdentityTokenToJSON(json: any): UserIdentityToken {
      return UserIdentityTokenToJSONTyped(json, false);
  }

  export function UserIdentityTokenToJSONTyped(value?: UserIdentityToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PolicyId': value['PolicyId'],
        'UaTypeId': value['UaTypeId'],
    };
}

