/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriterGroupMessageDataType
 */
export interface WriterGroupMessageDataType {
    /**
     * 
     * @type {string}
     * @memberof WriterGroupMessageDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the WriterGroupMessageDataType interface.
 */
export function instanceOfWriterGroupMessageDataType(value: object): value is WriterGroupMessageDataType {
    return true;
}

export function WriterGroupMessageDataTypeFromJSON(json: any): WriterGroupMessageDataType {
    return WriterGroupMessageDataTypeFromJSONTyped(json, false);
}

export function WriterGroupMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriterGroupMessageDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function WriterGroupMessageDataTypeToJSON(json: any): WriterGroupMessageDataType {
      return WriterGroupMessageDataTypeToJSONTyped(json, false);
  }

  export function WriterGroupMessageDataTypeToJSONTyped(value?: WriterGroupMessageDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

