/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriterGroupTransportDataType
 */
export interface WriterGroupTransportDataType {
    /**
     * 
     * @type {string}
     * @memberof WriterGroupTransportDataType
     */
    UaTypeId?: string;
}

/**
 * Check if a given object implements the WriterGroupTransportDataType interface.
 */
export function instanceOfWriterGroupTransportDataType(value: object): value is WriterGroupTransportDataType {
    return true;
}

export function WriterGroupTransportDataTypeFromJSON(json: any): WriterGroupTransportDataType {
    return WriterGroupTransportDataTypeFromJSONTyped(json, false);
}

export function WriterGroupTransportDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriterGroupTransportDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'UaTypeId': json['UaTypeId'] == null ? undefined : json['UaTypeId'],
    };
}

  export function WriterGroupTransportDataTypeToJSON(json: any): WriterGroupTransportDataType {
      return WriterGroupTransportDataTypeToJSONTyped(json, false);
  }

  export function WriterGroupTransportDataTypeToJSONTyped(value?: WriterGroupTransportDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UaTypeId': value['UaTypeId'],
    };
}

